### ISSUE TITLE
function `subplots_adjust` does nothing...

### ISSUE THREAD

**Issue by Datseris** [JuliaPy/PyPlot.jl#303]
```julia
using PyPlot
f = figure(1)

for j in 1:4
  subplot(2,2,j)
  plot(rand(10), rand(10))
end

# these lines do nothing for me, and I cannot understand why.
subplots_adjust(hspace = 0.01)
subplots_adjust(wspace = 0.01)

# maybe because when I see the picture, it looks like `tight_layout()` is on by default
# however, I looked at my matplotlibrc file this is nowhere stated...
```

Irrespectively of the numbers given to `subplots_adjust`, nothing happens.

**Comment by Datseris** [comment]
The function `tight_layout(pad=0.4, w_pad=0.5, h_pad=1.0)` also has no impact on my figure.

**Comment by stevengj** [comment]
What happens if you try the equivalent code in Python?

**Comment by Datseris** [comment]
I have no idea actually. I opened spyder but I could not make it work. `plt.figure()` could not produce a figure for the love of it, even if the console said that an object was created.
I've used all the combinations of `pylab.show()` , draw, etc. and the same from pyplot with show and interactive mode on, but I could not have a figure window appear no matter what.

Since I haven't used Python in over a year and I won't be using it in the future, I did not bother fixing it...

But does what I reported here work for you or not?

**Comment by stevengj** [comment]
They work fine for me (Julia 0.6, with the Conda.jl Python installation on MacOS), both as inline plots in IJulia and in a qt5agg backend window.  Without the `subplots_adjust` lines, I get:
![image](https://user-images.githubusercontent.com/2913679/27881209-cd9e43de-6195-11e7-8c25-73a6ac4286b4.png)
and with the `subplots_adjust` lines I get:
![image](https://user-images.githubusercontent.com/2913679/27881244-e2b9cd06-6195-11e7-83f0-395eeb7345e3.png)
So, I'm guessing that this is a problem with Matplotlib on your machine.

When there is a plotting glitch like this, I generally ask people to try it in Python to see whether the problem is in Matplotlib itself.

**Comment by stevengj** [comment]
If you don't want to maintain a working Python installation, especially on Windows or Mac, I highly recommend that you let Julia manage its own Python installation via Conda.  Do
```jl
ENV["PYTHON"]=""
using Conda
Conda.update()
Pkg.build("PyCall")
```
to make sure that PyCall is configured using Conda and that Conda is up-to-date.

**Comment by Datseris** [comment]
Thank you. I will do that then. Would you be so kind to tell where does Conda store the matplotlibrc file? I always change the default settings.

**Comment by stevengj** [comment]
Matplotlib will tell you this: just do `PyPlot.matplotlib[:matplotlib_fname]()`

**Comment by stevengj** [comment]
Actually, `matplotlib_fname` tells you the location of the currently active matplotlibrc.  If you haven't installed your own, this will be the one installed in Conda (in `site-packages/matplotlib/mpl-data/matplotlibrc`), but you don't want to edit that one because it will get overwritten when Conda is updated.  Instead, you want to copy it to `$HOME/.matplotlib/matplotlibrc` and edit it there, where `$HOME` is your home directory (`homedir()` in Julia).

**Comment by stevengj** [comment]
This is all described in the matplotlib docs: https://matplotlib.org/users/customizing.html#customizing-with-matplotlibrc-files

**Comment by Datseris** [comment]
Thank you, everything works fine now.

I also finally understood what the problem was!!! In the matplotlibrc file there is some configuration under FIGURE: 
`#figure.autolayout : False ` 
which I have set to `True` making almost every positional change impossible!
