### ISSUE TITLE
GUI Freezes when Julia is busy

### ISSUE THREAD

**Issue by jebej** [JuliaPy/PyPlot.jl#345]
I'm sure that's a well known problem (though I couldn't find any issues about it).

As the title says, when a plot window is open, but Julia is busy, it is not possible to interact with it. Is this something that is possible to fix?

**Comment by stevengj** [comment]
No, because the event loop only in a separate task ("green thread") not a true OS thread.    If you want to interact with the plot during a long computations, you have to give it some cycles, e.g. by calling `yield()` occasionally.

(If you are plotting in a Jupyter notebook, the other alternative is to use something like Plotly that does interaction with JavaScript, so that it doesn't need any cycles from Julia.)
